### ISSUE TITLE
Random scale excludes relationship between mean and WS variance

### ISSUE THREAD

**Issue by eldinidle** [reach-lab/MixWildGUI#10]
if there is no random scale, then “Specify the relationship between the mean and WS variance” (lower left corner on Stage 1 Configuration) should be grayed out – there is no possible relationship in this case.

**Comment by adityaponnada** [comment]
@eldinidle is it still the case?

**Comment by eldinidle** [comment]
@adityaponnada Yes this is still not fixed.

**Comment by eldinidle** [comment]
@adityaponnada Resolved
