### ISSUE TITLE
Stage 2 models can’t be run in any situations.

### ISSUE THREAD

**Issue by sweeptime** [reach-lab/MixWildGUI#115]
Hi,

I test stage 2 models, but I can't successfully run the models in any situations. The definition file preview still showed some errors (null value). Please check the attached. Thanks!

![Slide3](https://user-images.githubusercontent.com/55767621/98015294-7be5b280-1db1-11eb-98cf-ed4261e71bac.PNG)
![2020-11-03_085134](https://user-images.githubusercontent.com/55767621/98015639-dda61c80-1db1-11eb-86dd-52458a6128ea.png)

**Comment by rexli999** [comment]
I may need to be able to replicate your test to debug. Can you give me the dataset, and specify what regressors you used?
