### ISSUE TITLE
Executables need to be cleaned up or hidden

### ISSUE THREAD

**Issue by sweeptime** [reach-lab/MixWildGUI#122]
Hi,

MixWILD generated outputs and DEF files as well as executables (e.g., mixors.exe) in the document folder. As the discussion in the meeting on Jan. 26, these EXE files may need to be removed or hidden in a sub folder. Thanks!
![MixWILD_EXE](https://user-images.githubusercontent.com/55767621/106214905-a5ca2d80-6184-11eb-96ac-75b6c7ff667a.png)

**Comment by rexli999** [comment]
fixed
