### ISSUE TITLE
Check categorical outcomes, mixed with stage 1 outcome

### ISSUE THREAD

**Issue by rexli999** [reach-lab/MixWildGUI#130]

**Comment by sweeptime** [comment]
Hi Jixin,

Please pay attention on the cat/multinomial outcomes when using SEP data. The cats are not correctly showed in the interface as well as the DEF file. Thanks.

![2021-02-26_143443](https://user-images.githubusercontent.com/55767621/109362438-d95dad80-783f-11eb-89ea-30a2eda50a53.png)

**Comment by rexli999** [comment]
fixed
