### ISSUE TITLE
MEMLS label in Stage 1 Model Configuration

### ISSUE THREAD

**Issue by sweeptime** [reach-lab/MixWildGUI#132]
Hi,

Please switch the current label, "scale", to the new one, "WS Variance". This will make the terms more unified in MixWILD. 
Also, it would be great if you may line up the labels at both levels (Level 1 & Level 2). Thanks! 
![Stage1_MEMLS](https://user-images.githubusercontent.com/55767621/107413752-f7987f00-6ac5-11eb-8ae5-bf98e018483b.png)

Best,
Wei-Lin

**Comment by rexli999** [comment]
I made the change but I also noticed WS variance was previously purposefully set to "Scale" if intercept and slope is selected. The alignment is hard in this case.
