### ISSUE TITLE
Can't find the Stage 2 output name in MixWILD when using separate data

### ISSUE THREAD

**Issue by sweeptime** [reach-lab/MixWildGUI#147]
Hi Jixin,

This version has an error when running 2-stage model by using separate data sets. The stage 2 result window is blank while there   is a stage 2 output in the folder. As we discussed, this issue may occur when the package try to get "data2_stage2_output" but our output named after "data1_stage2_output". Our suggestion is to use the same prefix with both outputs. For example, we have data1 and data2. The output files should still use data1_stage1_output and data1_stage2_output. Thanks!  

![2021-07-13_102348](https://user-images.githubusercontent.com/55767621/125499350-91b1e618-d4ee-4b1e-afed-8d31458b51d5.png)
![2021-07-13_102510](https://user-images.githubusercontent.com/55767621/125499355-fc8cdfe6-b9ef-4c61-a43b-6fa61e19d7a0.png)
![2021-07-13_105003](https://user-images.githubusercontent.com/55767621/125501046-957e86de-450d-4f81-a2ea-6efe019bdff7.png)

Best,
Wei-Lin

**Comment by rexli999** [comment]
Fixed and waiting to be tested. The cause of this problem is the Fortran code named the stage 2 output file as the first dataset rather than second. I just changed the code to be consistent with the Fortran output name.
