### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by karenra** [reach-lab/MixWildGUI#35]
When no title is entered, two error message pop up in a row at the end of convergence (please see attached).
![screenshot 536](https://user-images.githubusercontent.com/44207760/47034055-23d8a680-d12b-11e8-8947-355bcaf4cfd7.png)
![screenshot 535](https://user-images.githubusercontent.com/44207760/47034057-23d8a680-d12b-11e8-82f5-fd142cc087de.png)
![screenshot 534](https://user-images.githubusercontent.com/44207760/47034058-23d8a680-d12b-11e8-864b-13335351193f.png)

There is no option for no interaction term between location and scale for the 2nd stage model.

**Comment by adityaponnada** [comment]
Thanks! Did you try to run with the title for the model?

**Comment by adityaponnada** [comment]
@karenra In the stage 2 config, did you see a check box right next to the run button that says "Interaction ..." ?

**Comment by karenra** [comment]
Hi, it may not be related to the title - both 1st and 2nd stage models were converged but still got the same error messages (I talked to Eldin and Jason the other day and that's what we guessed at first).

**Comment by karenra** [comment]
And no there's no option for the interaction of location and scale. I tried both Mixreg and Mixor but the option didn't appear. Please see attached.
![screenshot 538](https://user-images.githubusercontent.com/44207760/47034739-06a4d780-d12d-11e8-9f94-ee54983400dc.png)

**Comment by adityaponnada** [comment]
@karenra can you try our latest release and see if the issue is persistent. Moreover, can you share your def file so that i can replicate the error at my end?

**Comment by adityaponnada** [comment]
@karenra the fourth column in stage 2 is the interaction of location and scale. but that is enabled only when you include random location and random scale in the model. @eldinidle @ringineer correct me if I am wrong.
