### ISSUE TITLE
Suppress scale x random interaction

### ISSUE THREAD

**Issue by sweeptime** [reach-lab/MixWildGUI#61]
Hi,

I tried to suppress the interaction estimation between scale and location in MixWild Stage 2 model. I checked the button "Suppress scale x random interaction". However, it just popped out a warning window and it showed "Unassigned field or label series for one or more sets of options or regressors". Then, the output still showed that the interaction effect was included in the model. Please fix it and let me know how I can get the model without default interaction in Stage 2. Thanks.
![2019-09-24_141634](https://user-images.githubusercontent.com/55767621/65552687-e56e6e80-ded9-11e9-9fd2-9c3f72aeebbf.png)

**Comment by eldinidle** [comment]
Fixed
