### ISSUE TITLE
Can't run model using GUI

### ISSUE THREAD

**Issue by ringineer** [reach-lab/MixWildGUI#8]
![image](https://user-images.githubusercontent.com/36833482/36777463-2acfabfc-1c2f-11e8-84e9-3859d6c3d3d7.png)

When I saved the def file and copied it over to the folder where I had mixregls_random_mixor.exe that I built using that bat file, that worked fine.

I'm guessing this is a continuation of the issue where the windows binaries did not work when downloaded, but did when I created them myself. It's very odd...

**Comment by eldinidle** [comment]
Just to verify
1) You get the same error (warning window with red X) when you run this from CMD.
2) You replace the EXES, then rerun, and everything works fine.

Can you try the following?
1) Run an MD5 on the EXEs from here and from the file you built. Are they identical?
2) Run from CMD as Administrator, same error?

**Comment by ringineer** [comment]
I copied the def file into another folder.

I'm not sure where to find the executables being used by mixwild?

**Comment by adityaponnada** [comment]
@ringineer exes are in the resources.windows folder in the mixWILD src

**Comment by adityaponnada** [comment]
@ringineer https://github.com/reach-lab/MixWildGUI/tree/master/src/resources/WindowsNew

**Comment by ringineer** [comment]
Oh ok, I thought they had been copied as part of the installation.

Yes, the binaries for the combined files from github do not work.
Interestingly, the binaries copied over (mixor, mixreg, repeat_mixor,
repeat_mixreg, random_mix) run fine once I switch out the calling
executable.

I do not get the same thing from md5. Are there options I should be using?

[image: Inline image 1]

I am already an administrator on my home computer--do I need to do
something differently to run as administrator?

**Comment by adityaponnada** [comment]
No if it is already an administrator account, then you do not have to do anything. It may ask for log in info though. @ringineer

**Comment by adityaponnada** [comment]
@ringineer is this closed?

**Comment by adityaponnada** [comment]
@ringineer should we close this issue now?

**Comment by ringineer** [comment]
I still can't run them, but I've given up trying to figure out why, so go
ahead and close it.
