### ISSUE TITLE
MixLibrary.java questions

### ISSUE THREAD

**Issue by rexli999** [reach-lab/MixWildGUI#88]
Have a couple of questions on MixLibrary. Too many of them, I listed here a few. Thanks.
1. Is the setSharedDataFilename in MixLibrary the same with setDataFilename in DefinitionHelper ?
2. Not sure what this "setModelFixedInt();" does in line 5770 of mixregGUI.java? Also for the setModelRandomInt, setModelBetweenInt, setModelScaleInt, setModelWithinInt, not sure what to be mapped to in MixLibrary.
3. Should setAdvancedDiscardSubjects be mapped to setAdvancedDiscardNoVariance?
4. Should setSeedForStageTwo be mapped to setAdvancedResamplingSeed?
5. what should be mapped to in MixLibrary for setAdvancedRandomScaleNotIncluded ?
6. what should be mapped to in MixLibrary for setAdvancedDropSecondStage?
7. what should be mapped to in MixLibrary for setIdOutcome?
8. what should be mapped to in MixLibrary for setLabelModelOutcome?
9. what should be mapped to in MixLibrary for setModelMeanCount?
10. what should be mapped to in MixLibrary for setModelBetweenCount?
11. what should be mapped to in MixLibrary for setModelWithinCount?
12. what should be mapped to in MixLibrary for setDecompBSCount?
13. what should be mapped to in MixLibrary for setDecompWSCount?

**Comment by eldinidle** [comment]
1. Yes

2. These are set in the Advanced Options menu under Stage 1 Configuration. In MixLibrary setModelFixedInt is setAdvancedMeanIntercept, setModelRandomInt/setModelBetweenInt are now just one (setAdvancedRandomIntercept), and setModelScaleInt/setModelWithinInt are now just one (setAdvancedScaleIntercept).

**Comment by eldinidle** [comment]
3. Yes
4. Yes
5. advancedUseRandomScale
6. advancedUseStageTwo
7. setSharedIdAndStageOneOutcomeFields
8. setSharedModelStageOneOutcomeLabel
9. setAdvancedMeanRegressorCount
10. setAdvancedRandomRegressorCount (is also setModelRandomCount from DH.java)
11. setAdvancedScaleRegressorCount (is also setModelScaleCount from DH.java)
12. setAdvancedDecompseRandomRegressorCount
13. setAdvancedDecompseScaleRegressorCount

**Comment by eldinidle** [comment]
Let me know if you are free to talk to tomorrow via email.
